version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 999
  - package-ecosystem: github-actions
    directory: .github/workflows
    schedule:
      interval: weekly
    open-pull-requests-limit: 999
